spring:
  profiles:
    active: prod

server:
  forward-headers-strategy: native
  servlet:
    context-path: /api
  tomcat:
    mbeanregistry:
      enabled: true
    max-connections: 60000
    accept-count: 20000
    threads:
      max: 400

jwt:
  expirationAt: 3600000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

sse:
  timeout: 3600000